
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nurcan
 */
public class dilekistekyonetici extends javax.swing.JFrame {

    /**
     * Creates new form dilekistekyonetici
     */
    DefaultTableModel model ;
    
    public dilekistekyonetici() {
        initComponents();
        tabloyudoldur();
    }

    public void tabloyudoldur() //populatetable
    {
          model=(DefaultTableModel)tblogrenciler.getModel(); 
          model.setRowCount(0); 
        try {
            ArrayList<dilekistekclass> ogrenciler=getDilekistek();
            for(dilekistekclass ogr: ogrenciler )
            {
                Object[] row={ogr.getId(),ogr.getDilek()};
                model.addRow(row);
                        }
                    } catch (SQLException ex) {
            
        }
    }
    
    public ArrayList<dilekistekclass> getDilekistek() throws SQLException{
    Connection connection=null;
    dbHelper db=new dbHelper();
    Statement statement =null;
    ResultSet resultSet;
    ArrayList<dilekistekclass> ogrenciler =null;
    
    try{
        connection=db.getConnection();
        statement = connection.createStatement();
        resultSet=statement.executeQuery("select * from dilekistek");
        ogrenciler=new ArrayList<dilekistekclass>();
        
       while(resultSet.next())
     {
          ogrenciler.add(new dilekistekclass  
                ( resultSet.getInt("oda") , 
                  resultSet.getString("dilek")
                ));
     }
        
        
    }catch(SQLException exception)
     {
        
     }finally
    {
        statement.close();
        connection.close();
    }
    return ogrenciler;
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblogrenciler = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblogrenciler.setBackground(new java.awt.Color(204, 255, 204));
        tblogrenciler.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tblogrenciler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "oda", "dilek"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblogrenciler);
        if (tblogrenciler.getColumnModel().getColumnCount() > 0) {
            tblogrenciler.getColumnModel().getColumn(0).setResizable(false);
            tblogrenciler.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dilekistekyonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dilekistekyonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dilekistekyonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dilekistekyonetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dilekistekyonetici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblogrenciler;
    // End of variables declaration//GEN-END:variables
}
