public class etutodalari extends javax.swing.JFrame {

    /**
     * Creates new form etutodalari
     */
    public etutodalari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        masabir = new javax.swing.JCheckBox();
        masaiki = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        masauckatbir = new javax.swing.JCheckBox();
        masadortkatbir = new javax.swing.JCheckBox();
        masabeskatbir = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        masaikikatiki = new javax.swing.JCheckBox();
        masabirkatiki = new javax.swing.JCheckBox();
        masauckatiki = new javax.swing.JCheckBox();
        masadortkatiki = new javax.swing.JCheckBox();
        masabeskatiki = new javax.swing.JCheckBox();
        masabirlbl1 = new javax.swing.JLabel();
        masa31 = new javax.swing.JLabel();
        masa41 = new javax.swing.JLabel();
        masa51 = new javax.swing.JLabel();
        masabirkatikilbl = new javax.swing.JLabel();
        masaikikatikilbl = new javax.swing.JLabel();
        masauckatikilbl = new javax.swing.JLabel();
        masadortkatikilbl = new javax.swing.JLabel();
        masabeskatikilbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        masabirkatuc = new javax.swing.JCheckBox();
        masaikikatuc = new javax.swing.JCheckBox();
        masadortkatuc = new javax.swing.JCheckBox();
        masauckatuc = new javax.swing.JCheckBox();
        masabeskatuc = new javax.swing.JCheckBox();
        masabirkatuclbl = new javax.swing.JLabel();
        masaikikatuclbl = new javax.swing.JLabel();
        masauckatuclbl = new javax.swing.JLabel();
        masadortkatuclbl = new javax.swing.JLabel();
        masabeskatuclbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        masabirkatdort = new javax.swing.JCheckBox();
        masaikikatdort = new javax.swing.JCheckBox();
        masauckatdort = new javax.swing.JCheckBox();
        masadortkatdort = new javax.swing.JCheckBox();
        masabeskatdort = new javax.swing.JCheckBox();
        masabirkatdortlbl = new javax.swing.JLabel();
        masaikikatdortlbl = new javax.swing.JLabel();
        masauckatdortlbl = new javax.swing.JLabel();
        masadortkatdortlbl = new javax.swing.JLabel();
        masabeskatdortlbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        masabirkatbes = new javax.swing.JCheckBox();
        masaikikatbes = new javax.swing.JCheckBox();
        masauckatbes = new javax.swing.JCheckBox();
        masadortkatbes = new javax.swing.JCheckBox();
        masabeskatbes = new javax.swing.JCheckBox();
        masabirkatbeslbl = new javax.swing.JLabel();
        masaikikatbeslbl = new javax.swing.JLabel();
        masauckatbeslbl = new javax.swing.JLabel();
        masadortkatbeslbl = new javax.swing.JLabel();
        masabeskatbeslbl = new javax.swing.JLabel();
        masabirkatalti = new javax.swing.JCheckBox();
        masaikikatalti = new javax.swing.JCheckBox();
        masauckatalti = new javax.swing.JCheckBox();
        masadortkatalti = new javax.swing.JCheckBox();
        masabeskatalti = new javax.swing.JCheckBox();
        masabirkataltilbl = new javax.swing.JLabel();
        masaikikataltilbl = new javax.swing.JLabel();
        masauckataltilbl = new javax.swing.JLabel();
        masadortkataltilbl = new javax.swing.JLabel();
        masabeskataltilbl = new javax.swing.JLabel();
        masaikibir = new javax.swing.JLabel();
        masauckatbirlbl = new javax.swing.JLabel();
        masadortkatbirlbl = new javax.swing.JLabel();
        masabeskatbirlbl = new javax.swing.JLabel();
        masaikikatbirlbl = new javax.swing.JLabel();
        masabirkatbirlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        masabir.setText("1.masa");
        masabir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirActionPerformed(evt);
            }
        });

        masaiki.setText("2.masa");
        masaiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("KAT-1 ");

        masauckatbir.setText("3.masa");
        masauckatbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckatbirActionPerformed(evt);
            }
        });

        masadortkatbir.setText("4.masa");
        masadortkatbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkatbirActionPerformed(evt);
            }
        });

        masabeskatbir.setText("5.masa");
        masabeskatbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskatbirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("KAT-2");

        masaikikatiki.setText("2.masa");
        masaikikatiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikikatikiActionPerformed(evt);
            }
        });

        masabirkatiki.setText("1.masa");
        masabirkatiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirkatikiActionPerformed(evt);
            }
        });

        masauckatiki.setText("3.masa");
        masauckatiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckatikiActionPerformed(evt);
            }
        });

        masadortkatiki.setText("4.masa");
        masadortkatiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkatikiActionPerformed(evt);
            }
        });

        masabeskatiki.setText("5.masa");
        masabeskatiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskatikiActionPerformed(evt);
            }
        });

        masabirkatikilbl.setText("BOŞ!");

        masaikikatikilbl.setText("BOŞ!");

        masauckatikilbl.setText("DOLU!");

        masadortkatikilbl.setText("BOŞ!");

        masabeskatikilbl.setText("BOŞ!");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("KAT-3");

        masabirkatuc.setText("1.masa");
        masabirkatuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirkatucActionPerformed(evt);
            }
        });

        masaikikatuc.setText("2.masa");
        masaikikatuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikikatucActionPerformed(evt);
            }
        });

        masadortkatuc.setText("4.masa");
        masadortkatuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkatucActionPerformed(evt);
            }
        });

        masauckatuc.setText("3.masa");
        masauckatuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckatucActionPerformed(evt);
            }
        });

        masabeskatuc.setText("5.masa");
        masabeskatuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskatucActionPerformed(evt);
            }
        });

        masabirkatuclbl.setText("BOŞ!");

        masaikikatuclbl.setText("BOŞ!");

        masauckatuclbl.setText("DOLU!");

        masadortkatuclbl.setText("BOŞ!");

        masabeskatuclbl.setText("BOŞ!");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("KAT-4");

        masabirkatdort.setText("1.masa");
        masabirkatdort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirkatdortActionPerformed(evt);
            }
        });

        masaikikatdort.setText("2.masa");
        masaikikatdort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikikatdortActionPerformed(evt);
            }
        });

        masauckatdort.setText("3.masa");
        masauckatdort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckatdortActionPerformed(evt);
            }
        });

        masadortkatdort.setText("4.masa");
        masadortkatdort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkatdortActionPerformed(evt);
            }
        });

        masabeskatdort.setText("5.masa");
        masabeskatdort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskatdortActionPerformed(evt);
            }
        });

        masabirkatdortlbl.setText("BOŞ!");

        masaikikatdortlbl.setText("BOŞ!");

        masauckatdortlbl.setText("BOŞ!");

        masadortkatdortlbl.setText("DOLU!");

        masabeskatdortlbl.setText("BOŞ!");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("KAT-5");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("KAT-6");

        masabirkatbes.setText("1.masa");
        masabirkatbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirkatbesActionPerformed(evt);
            }
        });

        masaikikatbes.setText("2.masa");
        masaikikatbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikikatbesActionPerformed(evt);
            }
        });

        masauckatbes.setText("3.masa");
        masauckatbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckatbesActionPerformed(evt);
            }
        });

        masadortkatbes.setText("4.masa");
        masadortkatbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkatbesActionPerformed(evt);
            }
        });

        masabeskatbes.setText("5.masa");
        masabeskatbes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskatbesActionPerformed(evt);
            }
        });

        masabirkatbeslbl.setText("BOŞ!");

        masaikikatbeslbl.setText("BOŞ!");

        masauckatbeslbl.setText("BOŞ!");

        masadortkatbeslbl.setText("DOLU!");

        masabeskatbeslbl.setText("BOŞ!");

        masabirkatalti.setText("1.masa");
        masabirkatalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabirkataltiActionPerformed(evt);
            }
        });

        masaikikatalti.setText("2.masa");
        masaikikatalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaikikataltiActionPerformed(evt);
            }
        });

        masauckatalti.setText("3.masa");
        masauckatalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masauckataltiActionPerformed(evt);
            }
        });

        masadortkatalti.setText("4.masa");
        masadortkatalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masadortkataltiActionPerformed(evt);
            }
        });

        masabeskatalti.setText("5.masa");
        masabeskatalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masabeskataltiActionPerformed(evt);
            }
        });

        masabirkataltilbl.setText("DOLU!");

        masaikikataltilbl.setText("DOLU!");

        masauckataltilbl.setText("BOŞ!");

        masadortkataltilbl.setText("BOŞ!");

        masabeskataltilbl.setText("BOŞ!");

        masauckatbirlbl.setText("BOŞ!");

        masadortkatbirlbl.setText("BOŞ!");

        masabeskatbirlbl.setText("BOŞ");

        masaikikatbirlbl.setText("BOŞ!");

        masabirkatbirlbl.setText("BOŞ!");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("LÜTFEN BOŞ ALANLARI SEÇİNİZ ! ");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("ETÜT ODALARI");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etüt.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(masauckatbir)
                                .addGap(18, 18, 18)
                                .addComponent(masa31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(masaiki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(masabir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(masabirkatbirlbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masabirlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 33, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(masaikibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(masaikikatbirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masauckatiki)
                            .addComponent(masabirkatiki)
                            .addComponent(masaikikatiki)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masabeskatbir)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(masa51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(masabeskatbirlbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masabeskatiki))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masabeskatdort)
                        .addGap(18, 18, 18)
                        .addComponent(masabeskatdortlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masabeskatbes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(masabirkatdort))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(masabirkatdortlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(masabirkatbes))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masaikikatdort)
                        .addGap(18, 18, 18)
                        .addComponent(masaikikatdortlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masaikikatbes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masauckatdort)
                        .addGap(18, 18, 18)
                        .addComponent(masauckatdortlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masauckatbes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masadortkatdort)
                        .addGap(18, 18, 18)
                        .addComponent(masadortkatdortlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masadortkatbes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masadortkatbir)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(masa41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(masadortkatbirlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(82, 82, 82)))
                        .addComponent(masadortkatiki))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(masauckatbirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masabirkatikilbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(masabirkatbeslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masabirkatalti))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(masabeskatikilbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masabeskatuc))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(masadortkatikilbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masadortkatuc))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(masaikikatikilbl)
                                            .addComponent(masauckatikilbl))
                                        .addGap(79, 79, 79)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(masauckatuc)
                                            .addComponent(masaikikatuc)
                                            .addComponent(masabirkatuc)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(masaikikatbeslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masaikikatalti))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(masauckatbeslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masauckatalti))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(masadortkatbeslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masadortkatalti))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(masabeskatbeslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(masabeskatalti))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masaikikataltilbl)
                    .addComponent(masabirkataltilbl)
                    .addComponent(masauckataltilbl)
                    .addComponent(masadortkataltilbl)
                    .addComponent(masabeskataltilbl)
                    .addComponent(masaikikatuclbl)
                    .addComponent(masauckatuclbl)
                    .addComponent(masadortkatuclbl)
                    .addComponent(masabeskatuclbl)
                    .addComponent(masabirkatuclbl))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masabir)
                                .addComponent(masabirkatbirlbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masabirkatiki)
                                .addComponent(masabirkatikilbl)
                                .addComponent(masabirkatuc)
                                .addComponent(masabirkatuclbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masaiki)
                                .addComponent(masaikibir)
                                .addComponent(masaikikatbirlbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masaikikatiki)
                                .addComponent(masaikikatikilbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masaikikatuc)
                                .addComponent(masaikikatuclbl))))
                    .addComponent(masabirlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masauckatbir)
                        .addComponent(masauckatiki)
                        .addComponent(masa31)
                        .addComponent(masauckatikilbl)
                        .addComponent(masauckatbirlbl))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masauckatuc)
                        .addComponent(masauckatuclbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masadortkatbir)
                    .addComponent(masadortkatiki)
                    .addComponent(masa41)
                    .addComponent(masadortkatikilbl)
                    .addComponent(masadortkatuc)
                    .addComponent(masadortkatuclbl)
                    .addComponent(masadortkatbirlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masabeskatbir)
                    .addComponent(masabeskatiki)
                    .addComponent(masa51)
                    .addComponent(masabeskatikilbl)
                    .addComponent(masabeskatuc)
                    .addComponent(masabeskatuclbl)
                    .addComponent(masabeskatbirlbl))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masabirkatdort)
                    .addComponent(masabirkatdortlbl)
                    .addComponent(masabirkatbes)
                    .addComponent(masabirkatbeslbl)
                    .addComponent(masabirkatalti)
                    .addComponent(masabirkataltilbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masaikikatdort)
                    .addComponent(masaikikatdortlbl)
                    .addComponent(masaikikatbes)
                    .addComponent(masaikikatbeslbl)
                    .addComponent(masaikikatalti)
                    .addComponent(masaikikataltilbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masauckatdortlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masauckatdort)
                        .addComponent(masauckatbes)
                        .addComponent(masauckatbeslbl)
                        .addComponent(masauckatalti)
                        .addComponent(masauckataltilbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masadortkatdort)
                    .addComponent(masadortkatdortlbl)
                    .addComponent(masadortkatbes)
                    .addComponent(masadortkatbeslbl)
                    .addComponent(masadortkatalti)
                    .addComponent(masadortkataltilbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masabeskatdort)
                    .addComponent(masabeskatdortlbl)
                    .addComponent(masabeskatbes)
                    .addComponent(masabeskatbeslbl)
                    .addComponent(masabeskatalti)
                    .addComponent(masabeskataltilbl))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masabirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirActionPerformed
        
        if(masabir.isSelected())
        {
         masabirkatbirlbl.setText("DOLU!");
        }else
       {
           masabirkatbirlbl.setText("BOŞ!");
       }
        
    }//GEN-LAST:event_masabirActionPerformed

    private void masaikikatikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikikatikiActionPerformed
        // TODO add your handling code here:
        if(masaikikatiki.isSelected())
        {
         masaikikatikilbl.setText("DOLU!");
        }else
       {
           masaikikatikilbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masaikikatikiActionPerformed

    private void masauckatikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckatikiActionPerformed
        // TODO add your handling code here:
        
        if(masauckatikilbl.getText()=="DOLU!")
        {
          if(masauckatiki.isSelected())
        {
         masauckatikilbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
        
    }//GEN-LAST:event_masauckatikiActionPerformed

    private void masaikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikiActionPerformed
        // TODO add your handling code here:
       if(masaiki.isSelected())
        {
         masaikikatbirlbl.setText("DOLU!");
        }else
       {
           masaikikatbirlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masaikiActionPerformed

    private void masauckatbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckatbirActionPerformed
        // TODO add your handling code here:
        if(masauckatbir.isSelected())
        {
         masauckatbirlbl.setText("DOLU!");
        }else
       {
           masauckatbirlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masauckatbirActionPerformed

    private void masadortkatbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkatbirActionPerformed
        // TODO add your handling code here:
        if(masadortkatbir.isSelected())
        {
         masadortkatbirlbl.setText("DOLU!");
        }else
       {
           masadortkatbirlbl.setText("BOŞ!");
       }
        
    }//GEN-LAST:event_masadortkatbirActionPerformed

    private void masabeskatbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskatbirActionPerformed
        // TODO add your handling code here:
        if(masabeskatbir.isSelected())
        {
         masabeskatbirlbl.setText("DOLU!");
        }else
       {
           masabeskatbirlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabeskatbirActionPerformed

    private void masabirkatikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirkatikiActionPerformed
        // TODO add your handling code here:
        if(masabirkatiki.isSelected())
        {
         masabirkatikilbl.setText("DOLU!");
        }else
       {
           masabirkatikilbl.setText("BOŞ!");
       }
        
    }//GEN-LAST:event_masabirkatikiActionPerformed

    private void masadortkatikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkatikiActionPerformed
        // TODO add your handling code here:
        if(masadortkatiki.isSelected())
        {
         masadortkatikilbl.setText("DOLU!");
        }else
       {
           masadortkatikilbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masadortkatikiActionPerformed

    private void masabeskatikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskatikiActionPerformed
        // TODO add your handling code here:
        
        if(masabeskatiki.isSelected())
        {
         masabeskatikilbl.setText("DOLU!");
        }else
       {
           masabeskatikilbl.setText("BOŞ!");
       }
        
        
    }//GEN-LAST:event_masabeskatikiActionPerformed

    private void masabirkatucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirkatucActionPerformed
        // TODO add your handling code here:
        if(masabirkatuc.isSelected())
        {
         masabirkatuclbl.setText("DOLU!");
        }else
       {
           masabirkatuclbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabirkatucActionPerformed

    private void masaikikatucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikikatucActionPerformed
        // TODO add your handling code here:
        
        if(masaikikatuc.isSelected())
        {
         masaikikatuclbl.setText("DOLU!");
        }else
       {
           masaikikatuclbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masaikikatucActionPerformed

    private void masauckatucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckatucActionPerformed
        // TODO add your handling code here:
        if(masauckatuclbl.getText()=="DOLU!")
        {
          if(masauckatuc.isSelected())
        {
         masauckatuclbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
        
    }//GEN-LAST:event_masauckatucActionPerformed

    private void masadortkatucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkatucActionPerformed
        // TODO add your handling code here:
         if(masadortkatuc.isSelected())
        {
         masadortkatuclbl.setText("DOLU!");
        }else
       {
           masadortkatuclbl.setText("BOŞ!");
       }
        
    }//GEN-LAST:event_masadortkatucActionPerformed

    private void masabeskatucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskatucActionPerformed
        // TODO add your handling code here:
         if(masabeskatuc.isSelected())
        {
         masabeskatuclbl.setText("DOLU!");
        }else
       {
           masabeskatuclbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabeskatucActionPerformed

    private void masabirkatdortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirkatdortActionPerformed
        // TODO add your handling code here:
         if(masabirkatdort.isSelected())
        {
         masabirkatdortlbl.setText("DOLU!");
        }else
       {
         masabirkatdortlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabirkatdortActionPerformed

    private void masaikikatdortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikikatdortActionPerformed
        // TODO add your handling code here:
        if(masaikikatdort.isSelected())
        {
         masaikikatdortlbl.setText("DOLU!");
        }else
       {
         masaikikatdortlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masaikikatdortActionPerformed

    private void masauckatdortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckatdortActionPerformed
        // TODO add your handling code here:
        if(masauckatdort.isSelected())
        {
         masauckatdortlbl.setText("DOLU!");
        }else
       {
         masauckatdortlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masauckatdortActionPerformed

    private void masadortkatdortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkatdortActionPerformed
        // TODO add your handling code here:
        if(masadortkatdortlbl.getText()=="DOLU!")
        {
          if(masadortkatdort.isSelected())
        {
         masadortkatdortlbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
        
    }//GEN-LAST:event_masadortkatdortActionPerformed

    private void masabeskatdortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskatdortActionPerformed
        // TODO add your handling code here:
        if(masabeskatdort.isSelected())
        {
         masabeskatdortlbl.setText("DOLU!");
        }else
       {
         masabeskatdortlbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabeskatdortActionPerformed

    private void masabirkatbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirkatbesActionPerformed
        // TODO add your handling code here:
        if(masabirkatbes.isSelected())
        {
         masabirkatbeslbl.setText("DOLU!");
        }else
       {
         masabirkatbeslbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabirkatbesActionPerformed

    private void masaikikatbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikikatbesActionPerformed
        // TODO add your handling code here:
         if(masaikikatbes.isSelected())
        {
         masaikikatbeslbl.setText("DOLU!");
        }else
       {
         masaikikatbeslbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masaikikatbesActionPerformed

    private void masauckatbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckatbesActionPerformed
        // TODO add your handling code here:
         if(masauckatbes.isSelected())
        {
         masauckatbeslbl.setText("DOLU!");
        }else
       {
         masauckatbeslbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masauckatbesActionPerformed

    private void masadortkatbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkatbesActionPerformed
        // TODO add your handling code here:
        if(masadortkatbeslbl.getText()=="DOLU!")
        {
          if(masadortkatbes.isSelected())
        {
         masadortkatbeslbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
    }//GEN-LAST:event_masadortkatbesActionPerformed

    private void masabeskatbesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskatbesActionPerformed
        // TODO add your handling code here:
         if(masabeskatbes.isSelected())
        {
         masabeskatbeslbl.setText("DOLU!");
        }else
       {
         masabeskatbeslbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabeskatbesActionPerformed

    private void masauckataltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masauckataltiActionPerformed
        // TODO add your handling code here:
        if(masauckatalti.isSelected())
        {
         masauckataltilbl.setText("DOLU!");
        }else
       {
         masauckataltilbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masauckataltiActionPerformed

    private void masabirkataltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabirkataltiActionPerformed
        // TODO add your handling code here:
        if(masabirkataltilbl.getText()=="DOLU!")
        {
          if(masabirkatalti.isSelected())
        {
         masabirkataltilbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
    }//GEN-LAST:event_masabirkataltiActionPerformed

    private void masaikikataltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaikikataltiActionPerformed
        // TODO add your handling code here:
         if(masaikikataltilbl.getText()=="DOLU!")
        {
          if(masaikikatalti.isSelected())
        {
         masaikikataltilbl.setText("SEÇİLEMEZ(DOLU!)");
        }   
        }
    }//GEN-LAST:event_masaikikataltiActionPerformed

    private void masadortkataltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masadortkataltiActionPerformed
        // TODO add your handling code here:
        if(masadortkatalti.isSelected())
        {
         masadortkataltilbl.setText("DOLU!");
        }else
       {
         masadortkataltilbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masadortkataltiActionPerformed

    private void masabeskataltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masabeskataltiActionPerformed
        // TODO add your handling code here:
        if(masabeskatalti.isSelected())
        {
         masabeskataltilbl.setText("DOLU!");
        }else
       {
         masabeskataltilbl.setText("BOŞ!");
       }
    }//GEN-LAST:event_masabeskataltiActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(etutodalari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(etutodalari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(etutodalari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(etutodalari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new etutodalari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel masa31;
    private javax.swing.JLabel masa41;
    private javax.swing.JLabel masa51;
    private javax.swing.JCheckBox masabeskatalti;
    private javax.swing.JLabel masabeskataltilbl;
    private javax.swing.JCheckBox masabeskatbes;
    private javax.swing.JLabel masabeskatbeslbl;
    private javax.swing.JCheckBox masabeskatbir;
    private javax.swing.JLabel masabeskatbirlbl;
    private javax.swing.JCheckBox masabeskatdort;
    private javax.swing.JLabel masabeskatdortlbl;
    private javax.swing.JCheckBox masabeskatiki;
    private javax.swing.JLabel masabeskatikilbl;
    private javax.swing.JCheckBox masabeskatuc;
    private javax.swing.JLabel masabeskatuclbl;
    private javax.swing.JCheckBox masabir;
    private javax.swing.JCheckBox masabirkatalti;
    private javax.swing.JLabel masabirkataltilbl;
    private javax.swing.JCheckBox masabirkatbes;
    private javax.swing.JLabel masabirkatbeslbl;
    private javax.swing.JLabel masabirkatbirlbl;
    private javax.swing.JCheckBox masabirkatdort;
    private javax.swing.JLabel masabirkatdortlbl;
    private javax.swing.JCheckBox masabirkatiki;
    private javax.swing.JLabel masabirkatikilbl;
    private javax.swing.JCheckBox masabirkatuc;
    private javax.swing.JLabel masabirkatuclbl;
    private javax.swing.JLabel masabirlbl1;
    private javax.swing.JCheckBox masadortkatalti;
    private javax.swing.JLabel masadortkataltilbl;
    private javax.swing.JCheckBox masadortkatbes;
    private javax.swing.JLabel masadortkatbeslbl;
    private javax.swing.JCheckBox masadortkatbir;
    private javax.swing.JLabel masadortkatbirlbl;
    private javax.swing.JCheckBox masadortkatdort;
    private javax.swing.JLabel masadortkatdortlbl;
    private javax.swing.JCheckBox masadortkatiki;
    private javax.swing.JLabel masadortkatikilbl;
    private javax.swing.JCheckBox masadortkatuc;
    private javax.swing.JLabel masadortkatuclbl;
    private javax.swing.JCheckBox masaiki;
    private javax.swing.JLabel masaikibir;
    private javax.swing.JCheckBox masaikikatalti;
    private javax.swing.JLabel masaikikataltilbl;
    private javax.swing.JCheckBox masaikikatbes;
    private javax.swing.JLabel masaikikatbeslbl;
    private javax.swing.JLabel masaikikatbirlbl;
    private javax.swing.JCheckBox masaikikatdort;
    private javax.swing.JLabel masaikikatdortlbl;
    private javax.swing.JCheckBox masaikikatiki;
    private javax.swing.JLabel masaikikatikilbl;
    private javax.swing.JCheckBox masaikikatuc;
    private javax.swing.JLabel masaikikatuclbl;
    private javax.swing.JCheckBox masauckatalti;
    private javax.swing.JLabel masauckataltilbl;
    private javax.swing.JCheckBox masauckatbes;
    private javax.swing.JLabel masauckatbeslbl;
    private javax.swing.JCheckBox masauckatbir;
    private javax.swing.JLabel masauckatbirlbl;
    private javax.swing.JCheckBox masauckatdort;
    private javax.swing.JLabel masauckatdortlbl;
    private javax.swing.JCheckBox masauckatiki;
    private javax.swing.JLabel masauckatikilbl;
    private javax.swing.JCheckBox masauckatuc;
    private javax.swing.JLabel masauckatuclbl;
    // End of variables declaration//GEN-END:variables
}
