public class moduller extends javax.swing.JFrame {

    /**
     * Creates new form moduller
     */
    public moduller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        camasirhane = new javax.swing.JButton();
        yemekhanebtn = new javax.swing.JButton();
        etutodalaribtn = new javax.swing.JButton();
        izinbtn = new javax.swing.JButton();
        bosodalar = new javax.swing.JButton();
        ulasimaracsaatleri = new javax.swing.JButton();
        dilekistekbtn = new javax.swing.JButton();
        duyurularbtn = new javax.swing.JButton();
        sosyaletkinlikbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        yurtodemeleribtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        camasirhane.setBackground(new java.awt.Color(204, 204, 255));
        camasirhane.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        camasirhane.setText("ÇAMAŞIRHANE ");
        camasirhane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camasirhaneActionPerformed(evt);
            }
        });

        yemekhanebtn.setBackground(new java.awt.Color(204, 204, 255));
        yemekhanebtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        yemekhanebtn.setText("YEMEKHANE");
        yemekhanebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yemekhanebtnActionPerformed(evt);
            }
        });

        etutodalaribtn.setBackground(new java.awt.Color(204, 204, 255));
        etutodalaribtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        etutodalaribtn.setText("ETÜT ODALARI");
        etutodalaribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etutodalaribtnActionPerformed(evt);
            }
        });

        izinbtn.setBackground(new java.awt.Color(204, 204, 255));
        izinbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        izinbtn.setText("İZİN ALMA");
        izinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinbtnActionPerformed(evt);
            }
        });

        bosodalar.setBackground(new java.awt.Color(204, 204, 255));
        bosodalar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        bosodalar.setText("BOŞ ODALAR");
        bosodalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosodalarActionPerformed(evt);
            }
        });

        ulasimaracsaatleri.setBackground(new java.awt.Color(204, 204, 255));
        ulasimaracsaatleri.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ulasimaracsaatleri.setText("ULAŞIM  SAATLERİ");
        ulasimaracsaatleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulasimaracsaatleriActionPerformed(evt);
            }
        });

        dilekistekbtn.setBackground(new java.awt.Color(204, 204, 255));
        dilekistekbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        dilekistekbtn.setText("DİLEK-İSTEK");
        dilekistekbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilekistekbtnActionPerformed(evt);
            }
        });

        duyurularbtn.setBackground(new java.awt.Color(204, 204, 255));
        duyurularbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        duyurularbtn.setText("DUYURULAR");
        duyurularbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duyurularbtnActionPerformed(evt);
            }
        });

        sosyaletkinlikbtn.setBackground(new java.awt.Color(204, 204, 255));
        sosyaletkinlikbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        sosyaletkinlikbtn.setText("SOSYAL ETKİNLİKLER");
        sosyaletkinlikbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosyaletkinlikbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("BATTALGAZİ KIZ ÖĞRENCİ YURDU");

        yurtodemeleribtn.setBackground(new java.awt.Color(204, 204, 255));
        yurtodemeleribtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        yurtodemeleribtn.setText("YURT ÖDEMELERİ");
        yurtodemeleribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yurtodemeleribtnActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yemek2.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yurt.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etüt.png"))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(153, 0, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/çamaşırhane.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oda.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulaşım.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izin2.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dilek.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duyuru.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ödeme2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(etutodalaribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ulasimaracsaatleri)
                                    .addComponent(bosodalar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(camasirhane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(271, 271, 271))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(4, 4, 4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(yemekhanebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sosyaletkinlikbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yurtodemeleribtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(duyurularbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dilekistekbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yemekhanebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etutodalaribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(camasirhane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(dilekistekbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duyurularbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bosodalar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(ulasimaracsaatleri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(yurtodemeleribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(sosyaletkinlikbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(izinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etutodalaribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etutodalaribtnActionPerformed
        // TODO add your handling code here:
        etutodalari eo = new etutodalari();
        eo.setVisible(true);
    }//GEN-LAST:event_etutodalaribtnActionPerformed

    private void yemekhanebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yemekhanebtnActionPerformed
        // TODO add your handling code here:
        yemekhane ym=new yemekhane();
        ym.setVisible(true);
    }//GEN-LAST:event_yemekhanebtnActionPerformed

    private void camasirhaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camasirhaneActionPerformed
        // TODO add your handling code here:
        camasirhane c = new camasirhane();
        c.setVisible(true);
    }//GEN-LAST:event_camasirhaneActionPerformed

    private void ulasimaracsaatleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulasimaracsaatleriActionPerformed
        ulasim u = new ulasim();
        u.setVisible(true);
    }//GEN-LAST:event_ulasimaracsaatleriActionPerformed

    private void izinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinbtnActionPerformed
        // TODO add your handling code here:
        izinalma i = new izinalma();
        i.setVisible(true);
    }//GEN-LAST:event_izinbtnActionPerformed

    private void dilekistekbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilekistekbtnActionPerformed
        dilekistek di =new dilekistek();
        di.setVisible(true);
    }//GEN-LAST:event_dilekistekbtnActionPerformed

    private void duyurularbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duyurularbtnActionPerformed
        // TODO add your handling code here:
        duyurularogrenci duyuru = new duyurularogrenci();
        duyuru.setVisible(true);
    }//GEN-LAST:event_duyurularbtnActionPerformed

    private void sosyaletkinlikbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosyaletkinlikbtnActionPerformed
       sosyaletkinlik se= new sosyaletkinlik();
       se.setVisible(true);
        
    }//GEN-LAST:event_sosyaletkinlikbtnActionPerformed

    private void bosodalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosodalarActionPerformed
        bosOda oda= new bosOda();
        oda.setVisible(true);
    }//GEN-LAST:event_bosodalarActionPerformed

    private void yurtodemeleribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yurtodemeleribtnActionPerformed
        yurtOdemeleri y = new yurtOdemeleri();
        y.setVisible(true);
    }//GEN-LAST:event_yurtodemeleribtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moduller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bosodalar;
    private javax.swing.JButton camasirhane;
    private javax.swing.JButton dilekistekbtn;
    private javax.swing.JButton duyurularbtn;
    private javax.swing.JButton etutodalaribtn;
    private javax.swing.JButton izinbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sosyaletkinlikbtn;
    private javax.swing.JButton ulasimaracsaatleri;
    private javax.swing.JButton yemekhanebtn;
    private javax.swing.JButton yurtodemeleribtn;
    // End of variables declaration//GEN-END:variables
}
